eb_app:
    resource: "@EBAppBundle/Controller/"
    type:     annotation
    prefix:   /

eb_user:
    resource: "@EBUserBundle/Controller/"
    type:     annotation
    prefix:   /

# FOSUserBundle routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
