services:
    eb_user.registration.form.type:
        class: EB\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: eb_user_registration }

    eb_user.profile.form.type:
        class: EB\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: eb_user_profile }
